import { Component } from '@angular/core';
import { ReporteService } from './services/reporte.service';
import { ReporteGeneralService } from './services/reporte-general.service';
import { CertificadoElectoralPdfService } from './services/certificado-electoral-pdf.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  checked = false;
  indeterminate = false;
  labelPosition: 'before' | 'after' = 'after';
  disabled = false;
  title = 'reportenotas';
  element: any = [
    {
      curso:
        'METODOS Y TECNICAS DE INVESTIGACION EN CIENCIAS SOCIALES [176211]',
      docente: 'SOTO FLECHAS JUAN LISANDRO',
      grupo: '01',
      calendario: '20231A',
      evaluacion: 'Corte 01 [40.0%]',
      sede: 'NEIVA',
      estudiantes: null,
    },
  ];
  data: any = [
    {
      est_codigo: '20211195569',
      per_apellido: 'ACOSTA LOZANO',
      per_nombre: 'MANUELA MARIA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596600,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.8,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211198610',
      per_apellido: 'BENAVIDES SIERRA',
      per_nombre: 'HECTOR JAVIER',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596601,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.8,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197534',
      per_apellido: 'CAINAS QUIGUATENGO',
      per_nombre: 'HEDER DANILO',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596602,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.8,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211198792',
      per_apellido: 'CUBILLOS DIAZ',
      per_nombre: 'MARIA JOSE',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596603,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.8,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197649',
      per_apellido: 'FALLA BARREIRO',
      per_nombre: 'PAULA SOFIA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596604,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.5,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197309',
      per_apellido: 'FERREIRA ARCHIPIZ',
      per_nombre: 'MIGUEL ANGEL',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596605,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.5,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211198653',
      per_apellido: 'FORERO CARDENAS',
      per_nombre: 'JUAN CAMILO',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596606,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.5,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211198345',
      per_apellido: 'MAZABUEL OIDOR',
      per_nombre: 'ARLEX FABIAN',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596607,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.5,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211195626',
      per_apellido: 'MERCHAN BRAVO',
      per_nombre: 'KAREN JULIETTE',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596608,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.5,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211196663',
      per_apellido: 'MORALES ROJAS',
      per_nombre: 'STEPHANIA ',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596609,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.5,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211198309',
      per_apellido: 'NARANJO FERNANDEZ',
      per_nombre: 'HECTOR FABIAN',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596610,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.5,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211198287',
      per_apellido: 'OSORIO MONJE',
      per_nombre: 'DANIELA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596611,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.5,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197480',
      per_apellido: 'PUENTES HERNANDEZ',
      per_nombre: 'EDI SANTIAGO',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596612,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.5,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211198280',
      per_apellido: 'QUIN TOVAR',
      per_nombre: 'DIEGO FERNANDO',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596613,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 4.5,
        cun_fallas: 0,
        cun_observacion: '',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197094',
      per_apellido: 'ROJAS ROJAS',
      per_nombre: 'LUIS SANTIAGO',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596614,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197431',
      per_apellido: 'RUIZ SANABRIA',
      per_nombre: 'LIZETH NATALIA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596615,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197418',
      per_apellido: 'SANCHEZ ESPITIA',
      per_nombre: 'BLADIMIR',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596616,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211198474',
      per_apellido: 'SANCHEZ NINCO',
      per_nombre: 'YULI NATALIA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596617,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197777',
      per_apellido: 'SERRATO ALVAREZ',
      per_nombre: 'INDRA VALENTINNA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596618,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211195353',
      per_apellido: 'TRIANA OTAVO',
      per_nombre: 'MARIA JOSE',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596619,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211196147',
      per_apellido: 'VARGAS ANDRADE',
      per_nombre: 'VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596620,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
    {
      est_codigo: '20211197107',
      per_apellido: 'ZAMBRANO VERA',
      per_nombre: 'KAROL VANESSA',
      est_correo: 'daniela.alarcon@usco.edu.co',
      cursoNota: {
        cun_codigo: 596621,
        cun_estudiante: null,
        cun_evaluacion: 33882,
        cun_nota: 0,
        cun_fallas: 0,
        cun_observacion: 'Prueba',
        cun_propietario: 155458,
        cun_curso: 176211,
        cun_tipo_evaluacion: 0,
      },
    },
  ];

  dataGeneral: any = [
    {
      per_email: 'daniela.alarcon@usco.edu.co',
      codigo: '20212201591',
      nombre: 'BERDUGO CALDERON ANGELA',
      notas: [4.5],
      fallas: [0],
      definitiva: 1.8,
      mac_codigo: '4382046',
      mac_nota: null,
      mac_definitiva: null,
      perdio_fallas: false,
      cun_fallas: 0,
      cur_cierre: 1,
      cur_grabado: 0,
    },
    {
      per_email: 'daniela.alarcon@usco.edu.co',
      codigo: '20212201591',
      nombre: 'GERRERO CÓRODOBA JOHN',
      notas: [4.5, 4.2],
      fallas: [0, 0],
      definitiva: 1.8,
      mac_codigo: '4382046',
      mac_nota: null,
      mac_definitiva: null,
      perdio_fallas: false,
      cun_fallas: 0,
      cur_cierre: 1,
      cur_grabado: 0,
    },
    {
      per_email: 'daniela.alarcon@usco.edu.co',
      codigo: '20212201591',
      nombre: 'EMILLITO SEPULVEDA',
      notas: [4.5, 4.2, 4.1],
      fallas: [0, 0, 1],
      definitiva: 1.8,
      mac_codigo: '4382046',
      mac_nota: null,
      mac_definitiva: null,
      perdio_fallas: false,
      cun_fallas: 0,
      cur_cierre: 1,
      cur_grabado: 0,
    },
  ];

  constructor(
    public reporteService: ReporteService,
    public reporteGeneralService: ReporteGeneralService,
    public certificadoElectoralPdfService:CertificadoElectoralPdfService
  ) {}

  generarPdf() {
    this.reporteService.export(this.element, this.data);
  }

  generarPdfGeneral() {
    this.reporteGeneralService.export(this.element, this.dataGeneral);
  }

  generarCertificado() {
    this.certificadoElectoralPdfService.export(this.element);
  }

}
